from .disk import che_cd
from .disk import type_archivo
from .disk import get_free_space
from .disk import get_volume_info
from .disk import list_directory
from .disk import create_directory
from .disk import rename_directory
from .disk import delete_directory
from .disk import check_disk_space
from .disk import che_if
from .disk import exist